[package]
name = "experiment-normalisatie-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ego-tree = "0.6.2"
regex = "1.10.6"
scraper = "0.20.0"
